import { library } from '@fortawesome/fontawesome-svg-core';
import { faChrome, faGoogle } from '@fortawesome/free-brands-svg-icons';
import {
  faPlay,
  faStop,
  faEdit,
  faTrashAlt,
  faPlus,
  faTimes,
  faMinus,
  faPencilAlt,
  faSave,
  faCartPlus,
  faShoppingCart,
  faUser,
  faPaperPlane,
  faPowerOff,
  faFileImport,
  faEye,
  faEyeSlash,
  faClock,
  faProjectDiagram,
  faSyncAlt,
  faCog,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faChrome,
  faGoogle,
  faPlay,
  faStop,
  faEdit,
  faTrashAlt,
  faPlus,
  faTimes,
  faMinus,
  faPencilAlt,
  faSave,
  faCartPlus,
  faShoppingCart,
  faUser,
  faPaperPlane,
  faPowerOff,
  faFileImport,
  faEye,
  faEyeSlash,
  faClock,
  faProjectDiagram,
  faSyncAlt,
  faCog,
);
